site_name: Firecast Documentation
repo_url: https://github.com/Krampus-update/firecast-doc-teste

theme:
      name: material
      language: pt-BR
      favicon: img/favicon.ico
      features:
            - navigation.instant
            - navigation.path
            - toc.follow
            - header.autohide
            - navigation.top
            - navigation.sections
            - navigation.tracking
            - content.code.copy
            - content.code.select
            - content.code.annotate
            - content.tabs.link
            - navigation.footer
            - navigation.tabs
            - navigation.tabs.sticky
      palette:
            - scheme: default
              primary: custom
              toggle:
                    icon: material/brightness-7
                    name: Switch to dark mode
            - scheme: slate
              primary: custom
              toggle:
                    icon: material/brightness-4
                    name: Switch to light mode

extra:
        generator: false
        alternate:
        - name: English
          link: /en/ 
          lang: en
        - name: Portugues Brasileiro
          link: /pt/
          lang: pt-BR
        social:
        - icon: fontawesome/brands/discord
          link: https://discord.gg/YmsuYrhgyZ

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
      - "Introdução": "index.md"
      - "Primeiros Passos": "Primeirospassos.md"
      - "Histórico de Versões": "HistoricodeVersoes.md"
      - "Tutoriais":
              - "Criar um modelo de ficha à partir de um PDF": "CriarummodelodefichaapartirdeumP.md"
              - "Criar campos calculados em fichas": "Criarcamposcalculadosemfichas.md"
              - "Criar abas para a ficha": "Criarabasparaaficha.md"
              - "Permitir o usuário escolher uma imagem dentro da ficha": "Permitirousuarioescolherumaimage.md"
              - "Criar uma lista dinâmica na ficha": "Criarumalistadinamicanaficha.md"
              - "Fazer uma ficha enviar rolagens para a mesa": "Fazerumafichaenviarrolagensparaa.md"
              - "Criar uma lista dinâmica + painel de detalhes": "Criarumalistadinamicapaineldedet.md"
              - "Criar um botão que esconde itens de uma lista dinâmica": "Criarumbotaoqueescondeitensdeuma.md"
              - "Criar uma janela acoplável de mesa": "Criarumajanelaacoplaveldemesa.md"
              - "Criando um plug-in para vários idiomas": "Criandoumpluginparavariosidiomas.md"
      - "Referências":
              - "Projetos de Plug-in":
                      - "Criando um novo projeto de plug-in": "Criandoumnovoprojetodeplugin.md"
                      - "Testando o projeto de plug-in": "Testandooprojetodeplugin.md"
                      - "Disponibilizando um plug-in": "Disponibilizandoumplugin.md"
              - "Arquivos em um projeto de plug-in":
                      - 'O arquivo "module.xml"': "Oarquivomodulexml.md"
              - "Ferramentas do SDK 3":
                      - "Ferramenta rdk":
                              - 'comando "rdk p"': "comandordkp.md"
                              - 'comando "rdk c"': "comandordkc.md"
                              - 'comando "rdk i"': "comandordki.md"
                              - 'comando "rdk pdf"': "comandordkpdf.md"
                              - 'comando "rdk lfm"': "comandordklfm.md"
              - "Sandboxes de Plug-ins": "SandboxesdePlugins.md"
              - "Modelos de Fichas": "ModelosdeFichas.md"
              - "HD Virtual": "HDVirtual.md"
              - "NodeDatabase": "NodeDatabase.md"
              - "Arrastando e Soltando Informações / Drag And Drop": "ArrastandoeSoltandoInformacoesDr.md"
              - "Interfaces Visuais (Lua Forms)":
                      - "Guias":
                              - "Posição e Tamanho dos Controles": "PosicaoeTamanhodosControles.md"
                              - "Ponto Lógico vs Pixel": "PontoLogicovsPixel.md"
                              - "Orientações ao usar código LUA em um Lua Form": "OrientacoesaousarcodigoLUAemumLu.md"
                              - "Tratando eventos do Lua Form": "TratandoeventosdoLuaForm.md"
                              - "String de cores no Lua Form": "StringdecoresnoLuaForm.md"
                              - "Lua Form e NodeDatabase": "LuaFormeNodeDatabase.md"
                              - "Lua Form e Instâncias": "LuaFormeInstancias.md"
                              - "Estilos em Cascata": "EstilosemCascata.md"
                              - "Dividindo o arquivo Lua Form em documentos menores": "DividindooarquivoLuaFormemdocume.md"
                      - "Tags suportadas pelo Lua Form":
                              - "Características de todas as tags visuais": "Caracteristicasdetodasastagsvisu.md"
                              - "Características de todas as tags de textos": "Caracteristicasdetodasastagsdete.md"
                              - "Características de tags shapes": "Caracteristicasdetagsshapes.md"
                              - "Tag activityIndicator": "TagactivityIndicator.md"
                              - "Tag button": "Tagbutton.md"
                              - "Tag colorComboBox": "TagcolorComboBox.md"
                              - "Tag comboBox": "TagcomboBox.md"
                              - "Tag checkBox": "TagcheckBox.md"
                              - "Tag dataLink": "TagdataLink.md"
                              - "Tag dataScopeBox": "TagdataScopeBox.md"
                              - "Tag edit": "Tagedit.md"
                              - "Tag event": "Tagevent.md"
                              - "Tag flowLayout": "TagflowLayout.md"
                              - "Tag flowLineBreak": "TagflowLineBreak.md"
                              - "Tag flowPart": "TagflowPart.md"
                              - "Tag form": "Tagform.md"
                              - "Tag group": "Taggroup.md"
                              - "Tag horzLine": "TaghorzLine.md"
                              - "Tag image": "Tagimage.md"
                              - "Tag imageCheckBox": "TagimageCheckBox.md"
                              - "Tag import": "Tagimport.md"
                              - "Tag label": "Taglabel.md"
                              - "Tag layout": "Taglayout.md"
                              - "Tag path": "Tagpath.md"
                              - "Tag popup": "Tagpopup.md"
                              - "Tag popupForm": "TagpopupForm.md"
                              - "Tag progressBar": "TagprogressBar.md"
                              - "Tag radioButton": "TagradioButton.md"
                              - "Tag recordList": "TagrecordList.md"
                              - "Tag rectangle": "Tagrectangle.md"
                              - "Tag richEdit": "TagrichEdit.md"
                              - "Tag script": "Tagscript.md"
                              - "Tag scrollBox": "TagscrollBox.md"
                              - "Tag style": "Tagstyle.md"
                              - "Tag tab": "Tagtab.md"
                              - "Tag tabControl": "TagtabControl.md"
                              - "Tag template": "Tagtemplate.md"
                              - "Tag textEditor": "TagtextEditor.md"
                              - "Tag timer": "Tagtimer.md"
                      - "Frames":
                              - "Arquivo de Definição de Frame": "ArquivodeDefinicaodeFrame.md"
                              - "Frames e Regiões": "FrameseRegioes.md"
                              - "Exemplos de frames":
                                      - "1 - Background que estica para o novo tamanho": "1Backgroundqueesticaparaonovotam.md"
                                      - "2 - Background que se repete para preencher o tamanho": "2Backgroundqueserepeteparapreenc.md"
                                      - "3 - Frame com 2 partes fixas e 1 parte que se estica": "3Framecom2partesfixase1parteques.md"
                                      - "4 - Frame retangular dinâmico, usando vários arquivos de imagens": "4Frameretangulardinamicousandova.md"
                                      - "5 - Frame com regiões": "5Framecomregioes.md"
              - "Bibliotecas LUA":
                      - "Async.Promise library":
                              - "Promise object": "Promiseobject.md"
                      - "Biblioteca Dialogs": "BibliotecaDialogs.md"
                      - "Biblioteca FireDrive": "BibliotecaFireDrive.md"
                      - "Biblioteca GUI":
                              - "Objeto InertialMovement": "ObjetoInertialMovement.md"
                              - "Objeto Drag": "ObjetoDrag.md"
                              - "Objeto Drop": "ObjetoDrop.md"
                      - "Biblioteca Locale": "BibliotecaLocale.md"
                      - "Biblioteca Internet":
                              - "Objeto HTTPRequest": "ObjetoHTTPRequest.md"
                      - "Biblioteca NDB":
                              - "Objeto Nodo": "ObjetoNodo.md"
                              - "Objeto NodeObserver": "ObjetoNodeObserver.md"
                              - "Objeto NodeTransaction": "ObjetoNodeTransaction.md"
                              - "Objeto NodeUndoData": "ObjetoNodeUndoData.md"
                      - "Biblioteca Firecast":
                              - "Objeto Mesa": "ObjetoMesa.md"
                              - "Objeto Jogador": "ObjetoJogador.md"
                              - "Objeto Rolagem": "ObjetoRolagem.md"
                              - "Objeto BibliotecaItem": "ObjetoBibliotecaItem.md"
                              - "Objeto Personagem": "ObjetoPersonagem.md"
                              - "Objeto SceneUnitClass": "ObjetoSceneUnitClass.md"
                              - "Objeto Chat": "ObjetoChat.md"
                              - "Objeto WrappedObject": "ObjetoWrappedObject.md"
                      - "Biblioteca Firecast.Messaging":
                              - "Lista de Mensagens-Eventos do RRPG":
                                      - "Mensagens de Conexão": "MensagensdeConexao.md"
                                      - "Mensagens do Gerenciador de Plugins": "MensagensdoGerenciadordePlugins.md"
                                      - "Mensagens de Chat": "MensagensdeChat.md"
                                      - "Mensagens de Estado das Mesas": "MensagensdeEstadodasMesas.md"
                      - "Biblioteca Firecast.Plugins": "BibliotecaFirecastPlugins.md"
                      - "Biblioteca Firecast.Requests": "BibliotecaFirecastRequests.md"
                      - "Biblioteca SceneLib":
                              - "Visão geral da SceneLib": "VisaogeraldaSceneLib.md"
                              - "Métrica do Mundo vs Métrica da Tela": "MetricadoMundovsMetricadaTela.md"
                              - "As camadas do tabuleiro": "Ascamadasdotabuleiro.md"
                              - "Objeto Scene": "ObjetoScene.md"
                              - "Objeto SceneBaseObject": "ObjetoSceneBaseObject.md"
                              - "Objeto SceneCanvas": "ObjetoSceneCanvas.md"
                              - "Objeto SceneDrawingOp": "ObjetoSceneDrawingOp.md"
                              - "Objeto SceneDrawingOpBitmap": "ObjetoSceneDrawingOpBitmap.md"
                              - "Objeto SceneDawingOpPath": "ObjetoSceneDawingOpPath.md"
                              - "Objeto SceneDrawingOpText": "ObjetoSceneDrawingOpText.md"
                              - "Objeto SceneEffectArea": "ObjetoSceneEffectArea.md"
                              - "Objeto SceneFogOfWar": "ObjetoSceneFogOfWar.md"
                              - "Objeto SceneGraphicItem": "ObjetoSceneGraphicItem.md"
                              - "Objeto SceneGraphicItemList": "ObjetoSceneGraphicItemList.md"
                              - "Objeto SceneGridLayer": "ObjetoSceneGridLayer.md"
                              - "Objeto ScenePluginAttachment": "ObjetoScenePluginAttachment.md"
                              - "Objeto SceneUserDrawing": "ObjetoSceneUserDrawing.md"
                              - "Objeto SceneToken": "ObjetoSceneToken.md"
                              - "Objeto SceneViewport": "ObjetoSceneViewport.md"
                              - "Estrutura SceneRect": "EstruturaSceneRect.md"
                      - "Biblioteca System": "BibliotecaSystem.md"
                      - "Biblioteca Utils":
                              - "Objeto Stream": "ObjetoStream.md"
                      - "Biblioteca VHD": "BibliotecaVHD.md"
                      - "Log library": "Loglibrary.md"
      - "Macros":
              - "Biblioteca para Macros em Lua": "BibliotecaparaMacrosemLua.md"
      - "Apêndice":
              - "A linguagem de programação LUA": "AlinguagemdeprogramacaoLUA.md"
              - "Documentos XML": "DocumentosXML.md"
              - "FAQ -  Perguntas Frequentes": "FAQPerguntasFrequentes.md"
              - index.md
                - Apendice.md
                - Arquivosemumprojetodeplugin.md
                - AsyncPromiselibrary.md
                - BibliotecaFirecast.md
                - BibliotecaFirecastMessaging.md
                - BibliotecaGUI.md
                - BibliotecaInternet.md
                - BibliotecaNDB.md
                - BibliotecaSceneLib.md
                - BibliotecaUtils.md
                - BibliotecasLUA.md
                - Exemplosdeframes.md
                - Ferramentardk.md
                - FerramentasdoSDK3.md
                - Frames.md
                - Guias.md
                - InterfacesVisuaisLuaForms.md
                - ListadeMensagensEventosdoRRPG.md
                - Macros.md
                - ProjetosdePlugin.md
                - Referencias.md
                - TagssuportadaspeloLuaForm.md
                - Tutoriais.md
